version: '3.8'
services:
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
